### ISSUE TITLE
onComplete should have different api

### ISSUE THREAD

**Issue by funny-falcon** [dhruvrajvanshi/crystal-futures#1]
It is valid to set Exception as valid value for future, imho. So the kind of future's finishing should be determined in the way different from value's type check.

It could be two arguments: first is value, second is error. Another option : first is union of value and error (as it is now), and second argument is a boolean flag `ok`.

**Comment by dhruvrajvanshi** [comment]
Or it could be one argument of type Try(T) like scala
This would avoid the value from being nilable. The nil check is kind of a hassle in the language.
Here's how it would look in code

``` crystal
a.onComplete do |res|
  case res
  when Success
    puts res.value
  when Failure
    puts "Error"
  end
end
```

**Comment by funny-falcon** [comment]
Yes, this is also acceptable, if it could be done without additional allocation.

**Comment by dhruvrajvanshi** [comment]
It is not possible to do it without an allocation, but since the future is usually on relatively long running operations, the allocation time would be insignificant compared to that. As far as memory is concerned, the Try type would store only a reference to the actual object so, it would hardly matter.

**Comment by funny-falcon** [comment]
Which way Try(T) differs from future itself?

**Comment by dhruvrajvanshi** [comment]
Try(T) is a wrapper for a value(not a computation like future). It's concrete classes are Success(T) and Failure(T). It's value is set on creation(unlike future where the value may be set later).
Basically, onComplete handler is passed Success(T) if Future succeeds else it is passed Failure(T)
For Success(T), .value method returns the value of type T that it's holding.
For Failure(T), it contains the exception
You can pattern match over it to guarantee that it contains a value.

**Comment by funny-falcon** [comment]
``` ruby
a.onComplete do |fut|
  if fut.success?
    puts fut.value
  else
    puts "Error: #{fut.error}"
  end
end
```

**Comment by dhruvrajvanshi** [comment]
this should be fine. I'll update the code so that onComplete handler is called with the future itself

**Comment by dhruvrajvanshi** [comment]
I've made the changes
