### ISSUE TITLE
Why futures?

### ISSUE THREAD

**Issue by ghost** [dhruvrajvanshi/crystal-futures#2]
Since crystal has non-blocking io by default and has go's concurrency primitives like go routines you might not need futures.
 In a Go webserver each request will run in its own goroutine and the code inside that part can be blocking the runtime will handle the concurrency and parallelism for you.

I have rarely seen anyone use futures in Go.

**Comment by dhruvrajvanshi** [comment]
You may want to run your own synchronous computations in parallel and Futures are a nice abstraction to have. It may not necessarily be on a web server. Frankly, I can't think of a real use case on top of my head. I made this for learning purposes anyway.
