### ISSUE TITLE
Callback method naming

### ISSUE THREAD

**Issue by paulgoetze** [dhruvrajvanshi/crystal-futures#3]
I was just looking into this project's code and came across the [callbacks](https://github.com/dhruvrajvanshi/crystal-futures/blob/master/src/futures/future.cr#L112-L150).

I think the methods `onSuccess`, `onFailure`, and `onComplete` should rather be named `on_success`, `on_failure`, and `on_complete` in order to fit the crystal naming conventions for method naming.

**Comment by dhruvrajvanshi** [comment]
That's a good point. I was not very familiar with the ruby style naming before using crystal.
Will change it soon
